# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SFBC' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SFBC
  #pod 'AFNetworking', '~> 3.0'
  #pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'swift3'
  #pod 'GEOSwift', '~> 0.3.2'

  target 'SFBCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SFBCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
